micronaut:
    application:
        name: websocket-chat
    server:
      port: 12345
polyglot-scripts:
    python-init: "classpath:scripts/init.py"
    python-delayed-init: "classpath:scripts/nltk.py"
    python-venv: "classpath:venv/pyvenv.cfg"
---
#tag::static-resources[]
micronaut:
    router:
        static-resources: # <1>
            default:
                enabled: true
                mapping: /**
                paths: classpath:public
#end::static-resources[]
